'''This module contains any variables required for the program to run'''

CAMERA_VARIABLES = [
    'CAP_PROP_POS_MSEC',
    'CAP_PROP_POS_FRAMES',
    'CAP_PROP_POS_AVI_RATIO',
    'CAP_PROP_FRAME_WIDTH',
    'CAP_PROP_FRAME_HEIGHT',
    'CAP_PROP_FPS',
    'CV_CAP_PROP_FPS',
    'CAP_PROP_FOURCC',
    'CAP_PROP_FRAME_COUNT',
    'CAP_PROP_FORMAT',
    'CAP_PROP_MODE',
    'CAP_PROP_BRIGHTNESS',
    'CAP_PROP_CONTRAST',
    'CAP_PROP_SATURATION',
    'CAP_PROP_HUE',
    'CAP_PROP_GAIN',
    'CAP_PROP_EXPOSURE',
    'CAP_PROP_CONVERT_RGB',
    'CAP_PROP_WHITE_BALANCE',
    'CAP_PROP_RECTIFICATION',
]